name: TradingView RSI Capture

on:
  schedule:
    - cron: "0 * * * *" # Saatte 1
  workflow_dispatch:

jobs:
  capture:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Run capture
        run: |
          xvfb-run --auto-servernum node capture.js

      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: tv-screenshot
          path: tv_full.png
