- name: Run Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          SESSION_ID: ${{ secrets.SESSION_ID }}     # Burayı ekledik
          SESSION_SIGN: ${{ secrets.SESSION_SIGN }} # Burayı ekledik
        run: node capture.js
